all:
  hosts:
    master20-2:
      ansible_host: 10.20.1.2
      ip: 10.20.1.2
      access_ip: 10.20.1.2
    master20-3:
      ansible_host: 10.20.1.3
      ip: 10.20.1.3
      access_ip: 10.20.1.3
    worker10-2:
      ansible_host: 10.10.1.2
      ip: 10.10.1.2
      access_ip: 10.10.1.2
    worker10-3:
      ansible_host: 10.10.1.3
      ip: 10.10.1.3
      access_ip: 10.10.1.3
    worker40-2:
      ansible_host: 10.40.1.2
      ip: 10.40.1.2
      access_ip: 10.40.1.2
    worker40-3:
      ansible_host: 10.40.1.3
      ip: 10.40.1.3
      access_ip: 10.40.1.3
    worker40-4:
      ansible_host: 10.40.1.4
      ip: 10.40.1.4
      access_ip: 10.40.1.4
  children:
    kube_control_plane:
      hosts:
        master20-2:
        master20-3:
    kube_node:
      hosts:
        master20-2:
        master20-3:
        worker10-2:
        worker10-3:
        worker40-2:
        worker40-3:
        worker40-4:
    etcd:
      hosts:
        master20-2:
        master20-3:
        worker10-2:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
